#!/bin/bash
# Configure NTP servers for flightctl-onboarding
# Called via sudo by the onboarding user
# Usage:
#   configure-ntp.sh auto          - Clear custom servers, use system defaults
#   configure-ntp.sh set srv1 srv2 - Set custom NTP servers

set -e

ACTION="${1:?Usage: configure-ntp.sh auto|set [servers...]}"
shift

validate_server() {
    local srv="$1"
    if [[ ! "$srv" =~ ^[a-zA-Z0-9][a-zA-Z0-9.:-]*[a-zA-Z0-9]$|^[a-zA-Z0-9]$ ]]; then
        echo "Invalid NTP server name: $srv" >&2
        exit 1
    fi
}

configure_timesyncd_auto() {
    rm -f /etc/systemd/timesyncd.conf.d/50-cockpit.conf
    systemctl try-restart systemd-timesyncd.service >/dev/null 2>&1 || true
}

configure_timesyncd_set() {
    mkdir -p -m755 /etc/systemd/timesyncd.conf.d
    cat > /etc/systemd/timesyncd.conf.d/50-cockpit.conf <<EOF
# This file is automatically generated by Cockpit

[Time]
NTP=$*
EOF
    chmod 644 /etc/systemd/timesyncd.conf.d/50-cockpit.conf
    systemctl try-restart systemd-timesyncd.service >/dev/null 2>&1 || true
}

CHRONYD_SOURCEDIR_ADDED=false

ensure_chronyd_sourcedir() {
    if ! grep -q '^sourcedir /etc/chrony/sources.d' /etc/chrony.conf 2>/dev/null; then
        mkdir -p /etc/chrony/sources.d
        echo 'sourcedir /etc/chrony/sources.d' >> /etc/chrony.conf
        CHRONYD_SOURCEDIR_ADDED=true
    fi
}

reload_chronyd_sources() {
    if [ "$CHRONYD_SOURCEDIR_ADDED" = "true" ]; then
        systemctl try-restart chronyd.service >/dev/null 2>&1 || true
    else
        chronyc reload sources >/dev/null 2>&1 || true
    fi
}

configure_chronyd_auto() {
    ensure_chronyd_sourcedir
    rm -f /etc/chrony/sources.d/cockpit.sources /etc/chrony/sources.d/cockpit.disabled
    reload_chronyd_sources
}

configure_chronyd_set() {
    ensure_chronyd_sourcedir
    mkdir -p /etc/chrony/sources.d
    {
        echo "# This file is automatically generated by Cockpit"
        echo ""
        for srv in "$@"; do
            echo "server $srv iburst"
        done
    } > /etc/chrony/sources.d/cockpit.sources
    rm -f /etc/chrony/sources.d/cockpit.disabled
    reload_chronyd_sources
}

# Detect NTP backend: prefer the active/enabled service
BACKENDS=""
if systemctl is-active systemd-timesyncd.service >/dev/null 2>&1 || \
   systemctl is-enabled systemd-timesyncd.service >/dev/null 2>&1; then
    BACKENDS="timesyncd"
elif systemctl is-active chronyd.service >/dev/null 2>&1 || \
     systemctl is-enabled chronyd.service >/dev/null 2>&1; then
    BACKENDS="chronyd"
fi

# No active/enabled backend: configure all installed backends
if [ -z "$BACKENDS" ]; then
    systemctl list-unit-files chronyd.service >/dev/null 2>&1 && BACKENDS="$BACKENDS chronyd"
    systemctl list-unit-files systemd-timesyncd.service >/dev/null 2>&1 && BACKENDS="$BACKENDS timesyncd"
fi

if [ -z "$BACKENDS" ]; then
    if [ "$ACTION" = "auto" ]; then
        echo "NTP set to automatic (no supported backend found, skipping)"
        exit 0
    fi
    echo "No supported NTP backend found" >&2
    exit 1
fi

case "$ACTION" in
    auto)
        for backend in $BACKENDS; do
            if [ "$backend" = "timesyncd" ]; then
                configure_timesyncd_auto
            elif [ "$backend" = "chronyd" ]; then
                configure_chronyd_auto
            fi
        done
        echo "NTP set to automatic (backends: $BACKENDS)"
        ;;
    set)
        if [ $# -eq 0 ]; then
            echo "No servers specified" >&2
            exit 1
        fi
        for srv in "$@"; do
            validate_server "$srv"
        done
        for backend in $BACKENDS; do
            if [ "$backend" = "timesyncd" ]; then
                configure_timesyncd_set "$@"
            elif [ "$backend" = "chronyd" ]; then
                configure_chronyd_set "$@"
            fi
        done
        echo "NTP servers set: $* (backends: $BACKENDS)"
        ;;
    *)
        echo "Unknown action: $ACTION" >&2
        echo "Usage: configure-ntp.sh auto|set [servers...]" >&2
        exit 1
        ;;
esac
