#!/bin/bash
# Configure NTP servers for cockpit-system-onboarding
# Called via sudo by the onboarding user
# Usage:
#   configure-ntp.sh auto          - Clear custom servers, use system defaults
#   configure-ntp.sh set srv1 srv2 - Set custom NTP servers

set -e

ACTION="${1:?Usage: configure-ntp.sh auto|set [servers...]}"
shift

validate_server() {
    local srv="$1"
    if [[ ! "$srv" =~ ^[a-zA-Z0-9][a-zA-Z0-9.:-]*[a-zA-Z0-9]$|^[a-zA-Z0-9]$ ]]; then
        echo "Invalid NTP server name: $srv" >&2
        exit 1
    fi
}

# Detect NTP backend
if systemctl list-unit-files systemd-timesyncd.service >/dev/null 2>&1; then
    BACKEND="timesyncd"
elif systemctl list-unit-files chronyd.service >/dev/null 2>&1; then
    BACKEND="chronyd"
else
    echo "No supported NTP backend found" >&2
    exit 1
fi

case "$ACTION" in
    auto)
        if [ "$BACKEND" = "timesyncd" ]; then
            mkdir -p -m755 /etc/systemd/timesyncd.conf.d
            cat > /etc/systemd/timesyncd.conf.d/50-cockpit.conf <<'EOF'
# This file is automatically generated by Cockpit

[Time]
NTP=
EOF
            chmod 644 /etc/systemd/timesyncd.conf.d/50-cockpit.conf
        elif [ "$BACKEND" = "chronyd" ]; then
            rm -f /etc/chrony/sources.d/cockpit.sources /etc/chrony/sources.d/cockpit.disabled
        fi
        echo "NTP set to automatic (backend: $BACKEND)"
        ;;
    set)
        if [ $# -eq 0 ]; then
            echo "No servers specified" >&2
            exit 1
        fi
        for srv in "$@"; do
            validate_server "$srv"
        done
        if [ "$BACKEND" = "timesyncd" ]; then
            mkdir -p -m755 /etc/systemd/timesyncd.conf.d
            cat > /etc/systemd/timesyncd.conf.d/50-cockpit.conf <<EOF
# This file is automatically generated by Cockpit

[Time]
NTP=$*
EOF
            chmod 644 /etc/systemd/timesyncd.conf.d/50-cockpit.conf
        elif [ "$BACKEND" = "chronyd" ]; then
            mkdir -p /etc/chrony/sources.d
            {
                echo "# This file is automatically generated by Cockpit"
                echo ""
                for srv in "$@"; do
                    echo "server $srv"
                done
            } > /etc/chrony/sources.d/cockpit.sources
            rm -f /etc/chrony/sources.d/cockpit.disabled
        fi
        echo "NTP servers set: $* (backend: $BACKEND)"
        ;;
    *)
        echo "Unknown action: $ACTION" >&2
        echo "Usage: configure-ntp.sh auto|set [servers...]" >&2
        exit 1
        ;;
esac
