# Enable RPM builds and running integration tests in PRs through https://packit.dev/
# To use this, enable Packit-as-a-service in GitHub: https://packit.dev/docs/packit-as-a-service/
# See https://packit.dev/docs/configuration/ for the format of this file

downstream_package_name: flightctl-onboarding
specfile_path: flightctl-onboarding.spec
# use the nicely formatted release description from our upstream release, instead of git shortlog
copy_upstream_release_description: true

srpm_build_deps:
  - make
  - nodejs-npm

actions:
  post-upstream-clone:
    - make flightctl-onboarding.spec
    # replace Source1 manually, as create-archive: can't handle multiple tarballs
    - make node-cache
    - sh -c 'sed -i "/^Source1:/ s/https:.*/$(ls *-node*.tar.xz)/" flightctl-onboarding.spec'
  create-archive: make dist
  get-current-version:
    - bash -c './hack/current-version | sed "s/^v//; s/-/~/g"'

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-43-x86_64
      - epel-9-x86_64
      - epel-10-x86_64
    module_hotfixes: true
    notifications:
      failure_comment:
        message: "/packit build"

  - job: copr_build
    trigger: commit
    branch: main
    owner: "@redhat-et"
    project: flightctl-dev
    preserve_project: true
    targets: &copr_targets
      - fedora-42-x86_64
      - fedora-43-x86_64
      - epel-9-x86_64
      - epel-10-x86_64

  - job: copr_build
    trigger: release
    owner: "@redhat-et"
    project: flightctl
    preserve_project: true
    targets: *copr_targets
